// CMOS AND2 Gate
`include nand2.module
`include not.module

module AND2(in1, in2, out, vdd, gnd);
    parameter real WN=10u;
    parameter real WP=20u;
    parameter real L=0.09u;
    input in1, in2;
    output out;
    electrical in1, in2, out, vdd, gnd;

    NAND2 #(.WN(WN), .WP(WP), .L(L)) XNAND2(in1, in2, out1, vdd, gnd);
    NOT #(.WN(WN), .WP(WP), .L(L)) XNOT(out1, out, vdd, gnd);
endmodule





